version: '3.8'

services:
  redis-master:
    image: redis:8.2.1
    container_name: redis-master
    ports:
      - "6379:6379"
    networks:
      - redis-network
    volumes:
      - ./.data/redis-master-data:/data
 
  redis-slave:
    image: redis:8.2.1
    container_name: redis-slave
    ports:
      - "6380:6379"
    networks:
      - redis-network
    command: redis-server --slaveof redis-master 6379
    volumes:
      - ./.data/redis-slave-data:/data
 
networks:
  redis-network:
    driver: bridge
