services:
  mongodb:
    image: mongo:7.0.8
    container_name: mongodb
    restart: always
    environment:
        - MONGO_INITDB_DATABASE=admin
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=123456
    # volumes:
    #     - ./conf/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    #     - ./.data/mongo-volume:/data/db
    ports:
      - 27017:27017
  