services:
  mysql:
    image: mysql:8.4.6
    container_name: mysql
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always